### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by gokaygurcan** [progit/progit2-tr#4]
Merhaba,

3 yıldan sonra birden -ve arka arkaya- bildirim görünce çok şaşırdım açıkçası. Eğer çeviri konusunda destek olmak ve kitabı tamamlamak isterseniz, öncelikle repository'yi en güncel hale çekip sonrasında başlamayı teklif ediyorum. Hatta doğru düzgün milestone'lar belirleyerek yönetilebilir bir hale de getirebiliriz projeyi.

Konu hakkındaki görüşlerinizi duymayı çok isterim. 

Sevgiler,
G.

/cc @VitruvianManSteemit  && @sweedixie

**Comment by gokaygurcan** [comment]
Tekrar merhaba,

Repository'yi en güncel hale getirince kaçınılmaz olarak merge conflict ile karşılaştım; fakat şu anda hem İngilizce hallerinde değişiklik olabileceği hem de iki farklı Türkçe çeviri olabileceği için dosyaların var olan ve en güncel İngilizce hallerini içeren şekilde koymaya, sonrasında güncel Türkçe  versiyonlarına geçmeye karar verdim. 

Göz atılması ve doğruluğundan emin olunması gereken dosyaların listesi şöyle:

- [ ] ch01-getting-started.asc 
- [ ] book/01-introduction/sections/about-version-control.asc 
- [ ] book/01-introduction/sections/basics.asc 
- [ ] book/01-introduction/sections/command-line.asc 
- [ ] book/01-introduction/sections/help.asc 
- [ ] book/01-introduction/sections/history.asc 
- [ ] book/01-introduction/sections/installing.asc 

PR'ları güncellerseniz harika olur, yap(a)mazsanız da fırsat bulduğum gibi ben yaparım. 

Şimdiden teşekkürler,
G.

**Comment by gokaygurcan** [comment]
```
$ rake
Converting to HTML...
asciidoctor: WARNING: book/01-introduction/sections/about-version-control.asc: line 24: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: book/01-introduction/sections/about-version-control.asc: line 79: section title out of sequence: expected level 2, got level 3
asciidoctor: ERROR: book/03-git-branching/sections/basic-branching-and-merging.asc: line 312: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/03-git-branching/sections/basic-branching-and-merging.asc: line 313: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/03-git-branching/sections/basic-branching-and-merging.asc: line 314: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/04-git-server/sections/setting-up-server.asc: line 66: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: WARNING: book/04-git-server/sections/git-daemon.asc: line 30: invalid style for paragraph: Unit
asciidoctor: WARNING: book/04-git-server/sections/git-daemon.asc: line 33: invalid style for paragraph: Service
asciidoctor: WARNING: book/04-git-server/sections/git-daemon.asc: line 46: invalid style for paragraph: Install
asciidoctor: WARNING: book/04-git-server/sections/gitweb.asc: line 21: invalid style for listing block: 2009-02-21 10:02:21] INFO  ruby 1.8.6 (2008-03-03) [universal-darwin9.0
asciidoctor: ERROR: book/05-distributed-git/sections/contributing.asc: line 115: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/05-distributed-git/sections/contributing.asc: line 130: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/05-distributed-git/sections/contributing.asc: line 145: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/05-distributed-git/sections/contributing.asc: line 161: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/05-distributed-git/sections/contributing.asc: line 228: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/05-distributed-git/sections/contributing.asc: line 341: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: book/05-distributed-git/sections/contributing.asc: line 367: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: WARNING: progit.asc: line 58: invalid style for paragraph: imap
asciidoctor: WARNING: progit.asc: line 87: invalid style for paragraph: sendemail
asciidoctor: WARNING: progit.asc: line 14625: invalid style for paragraph: submodule "DbConnector"
asciidoctor: WARNING: progit.asc: line 15899: invalid style for paragraph: credential
asciidoctor: WARNING: progit.asc: line 16173: invalid style for listing block: Ticket: X
asciidoctor: WARNING: progit.asc: line 16195: invalid style for paragraph: Ticket: X
asciidoctor: WARNING: progit.asc: line 16398: invalid style for paragraph: merge
asciidoctor: WARNING: progit.asc: line 16400: invalid style for paragraph: mergetool "extMerge"
asciidoctor: WARNING: progit.asc: line 16403: invalid style for paragraph: diff
asciidoctor: WARNING: progit.asc: line 17437: invalid style for paragraph: master e05c914] test [ref: 132
asciidoctor: ERROR: progit.asc: line 40: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
 -- HTML output at progit.html
Converting to EPub...
asciidoctor: ERROR: ch01-getting-started.asc: line 3: only book doctypes can contain level 0 sections
asciidoctor: WARNING: book/01-introduction/sections/about-version-control.asc: line 24: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: book/01-introduction/sections/about-version-control.asc: line 79: section title out of sequence: expected level 1, got level 2
/Users/gokaygurcan/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
asciidoctor: WARNING: ch01-getting-started.asc: invalid reference to unknown local anchor (or valid bibref): _git_branching
asciidoctor: WARNING: ch01-getting-started.asc: invalid reference to unknown local anchor (or valid bibref): _git_branching
asciidoctor: WARNING: ch01-getting-started.asc: invalid reference to unknown local anchor (or valid bibref): _undoing
asciidoctor: WARNING: ch01-getting-started.asc: invalid reference to unknown local anchor (or valid bibref): _git_basics_chapter
/Users/gokaygurcan/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
asciidoctor: WARNING: ch02-git-basics-chapter.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: ch03-git-branching.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: ch03-git-branching.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: ch08-customizing-git.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: C-git-commands.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: C-git-commands.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
 -- Epub output at progit.epub
Converting to Mobi (kf8)...
asciidoctor: ERROR: ch01-getting-started.asc: line 3: only book doctypes can contain level 0 sections
asciidoctor: WARNING: book/01-introduction/sections/about-version-control.asc: line 24: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: book/01-introduction/sections/about-version-control.asc: line 79: section title out of sequence: expected level 1, got level 2
/Users/gokaygurcan/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
asciidoctor: WARNING: ch01-getting-started.asc: invalid reference to unknown local anchor (or valid bibref): _git_branching
asciidoctor: WARNING: ch01-getting-started.asc: invalid reference to unknown local anchor (or valid bibref): _git_branching
asciidoctor: WARNING: ch01-getting-started.asc: invalid reference to unknown local anchor (or valid bibref): _undoing
asciidoctor: WARNING: ch01-getting-started.asc: invalid reference to unknown local anchor (or valid bibref): _git_basics_chapter
/Users/gokaygurcan/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
asciidoctor: WARNING: ch02-git-basics-chapter.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: ch03-git-branching.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: ch03-git-branching.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: ch08-customizing-git.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: C-git-commands.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
asciidoctor: WARNING: C-git-commands.asc: invalid reference to anchor in unknown chapter: ch01-getting-started
 -- Mobi output at progit.mobi
Converting to PDF... (this one takes a while)
 -- PDF output at progit.pdf
```

Muhtemelen güncelleme ve merge conflict'ler arasında bazı yerlerde sorunlar oluşmuş. Onları da buraya koymuş olalım ki sonra kontrol eder, çözülüp çözülmediklerine bakarız.

**Comment by VitruvianManSteemit** [comment]
Merhaba, mailinizi yeni gördüm. Dosyaları tekrar düzenlemişsiniz. Ben de
PR'i geri çekip güncel halini alıp aynı dosyaya tekrardan PR yaptım.
Böylesi daha düzenli oldu sanırım. Düzenli bir şekilde kitabı yapıp
bitirmeyi düşünüyorum. Bu arada çeviri amacından da kısaca bahsetmek
isterim. Utopian.io isimli platform açık kaynaklı projelere destek veriyor.
Bizler Utopian bünyesi olarak açık kaynaklı projelere çeviriler yapıyoruz.
Bu projeyi Github'da bulup inceledim oldukça hoşuma gitti. Bu yüzden
çevirisine başlamak istedim. Siz PR'i onayladıktan sonra ben Utopian
sisteminde bunu paylaşacağım. Paylaştıktan sonra bir çok insan çeviri için
PR yapmaya başlayacaktır. İnsanlar genelde başkalarının çeviri yaptığı
projeleri görüp dahil oluyorlar. Bu noktada çevirileri dikkatle
incelemenizi öneririm. Bir çok kullanıcı maalesef direkt olarak Google
Translate'deki çeviriyi alıp olduğu gibi yapıştırıyor. Bu da maalesef kötü
çevirilerin ortaya çıkmasına sebep oluyor. Ben çevirileri Crowdin üzerinden
yapıyordum. Artık Github üzerinden yapmaya karar verdim. Ortalama 30 adet
açık kaynaklı projeye Türkçe dil desteği sağladım. Aşağıda Crowdin
profilimin ve Utopian platformunun linkini bırakacağım. Oradan
inceleyebilirsiniz. Şuanda Phalcon Documentation projesinde Proofreaderım.
Hem projeye çeviri yapıyor hem de yapılan çevirileri kontrol edip onay/red
veriyorum. (Çeviri kalitesine göre.) Benim bu projeyi paylaşmamla birlikte
bir çok kullanıcı PR isteği atacağından tüm istekleri kontrol etmekte
zorlanabilirsiniz. Bu bağlamda mevcut istek sayısı fazla gelirse sizin
projeniz için de hem çeviri hem de proofreaderlık yapabilirim. Mail
üzerinden 7/24 bana ulaşabilirsiniz. Projenize her daim yardımcı olmaktan
mutluluk duyarım. Görüşmek üzere.

Crowdin Profilim: https://crowdin.com/profile/vitruvianman
Utopian Platformu: https://utopian.io/
<https://crowdin.com/profile#>

2018-02-13 22:49 GMT+03:00 Gökay Gürcan <notifications@github.com>:

**Comment by aligoren** [comment]
@gokaygurcan Merhaba.

Telegram uzerindeki Linux Mafyasi kanalinda sordum. Eger guzel bir ekip toplanabilirse bu projeye sifirdan baslayalim diyorum sifirdan kastim aslinda guncel halini baz alip, eksik noktalari tamamlamak.

**Comment by jnavila** [comment]
Just to chim in: the book in Turkish is presently compiled with an automatic script here:
https://travis-ci.org/progit/progit2-tr

and deployed here:

https://git-scm.com/book/tr/v2

So, you just have to translate, push on branch, verify that you have not broken the markup (asciidoc can be treacherous) and if everything is fine, merge in master. The next day, your work is visible on git-scm.com.

**Comment by gokaygurcan** [comment]
Merhaba @aligoren, 
Tatildeydim, ancak cevap verebiliyorum. Benim için her türlü yol uygun, yeter ki destek verecek birileri olsun. 

@jnavila I was on holiday and just came back. I'll take care of the repository and update it to its latest version. From there, we can start working on it. Sorry for late reply. Will keep you posted.

**Comment by aligoren** [comment]
@gokaygurcan Bi soralim, sanirim bi kac arkadas toparlayabiliriz ne kadar ilerletebilirsek o kadar iyi, fazla, azdan iyidir diyelim :)

@jnavila we're trying to find translators for the Turkish language. I think I'll find some volunteers ASAP.

**Comment by gokaygurcan** [comment]
Since we're back on track and build process is back to normal, we can continue. Closing this issue now because it's not relevant anymore. 

/link #19
